-- Dev-only repeatable SO skill dictionary seed.
-- Loaded via %dev Flyway location: classpath:db/dev
-- Source: Stack Overflow Developer Survey 2025

DELETE FROM skills.skill_definition;

INSERT INTO skills.skill_definition (name, aliases, usage_count)
VALUES
    ('.net 8 or higher', ARRAY['.NET 8 or higher'], 0),
    ('apt', ARRAY['APT'], 0),
    ('asp.net', ARRAY['ASP.NET'], 0),
    ('asp.net core', ARRAY['ASP.NET Core'], 0),
    ('ada', ARRAY['Ada'], 0),
    ('aider', ARRAY['Aider'], 0),
    ('airtable', ARRAY['Airtable'], 0),
    ('alibaba cloud qwen models', ARRAY['Alibaba Cloud Qwen models'], 0),
    ('amazon bedrock', ARRAY['Amazon Bedrock'], 0),
    ('amazon redshift', ARRAY['Amazon Redshift'], 0),
    ('amazon titan models', ARRAY['Amazon Titan models'], 0),
    ('amazon web services (aws)', ARRAY['Amazon Web Services (AWS)'], 0),
    ('android', ARRAY['Android'], 0),
    ('android studio', ARRAY['Android Studio'], 0),
    ('angular', ARRAY['Angular'], 0),
    ('angularjs', ARRAY['AngularJS'], 0),
    ('ansible', ARRAY['Ansible'], 0),
    ('anthropic: claude sonnet', ARRAY['Anthropic: Claude Sonnet'], 0),
    ('arch', ARRAY['Arch'], 0),
    ('asana', ARRAY['Asana'], 0),
    ('assembly', ARRAY['Assembly'], 0),
    ('astro', ARRAY['Astro'], 0),
    ('axum', ARRAY['Axum'], 0),
    ('azure devops', ARRAY['Azure Devops'], 0),
    ('bash/shell (all shells)', ARRAY['Bash/Shell (all shells)'], 0),
    ('bigquery', ARRAY['BigQuery'], 0),
    ('blazor', ARRAY['Blazor'], 0),
    ('bluesky', ARRAY['Bluesky'], 0),
    ('bolt', ARRAY['Bolt'], 0),
    ('bun', ARRAY['Bun'], 0),
    ('c', ARRAY['C'], 0),
    ('c#', ARRAY['C#'], 0),
    ('c++', ARRAY['C++'], 0),
    ('cobol', ARRAY['COBOL'], 0),
    ('cargo', ARRAY['Cargo'], 0),
    ('cassandra', ARRAY['Cassandra'], 0),
    ('chocolatey', ARRAY['Chocolatey'], 0),
    ('chromeos', ARRAY['ChromeOS'], 0),
    ('claude code', ARRAY['Claude Code'], 0),
    ('clickhouse', ARRAY['Clickhouse'], 0),
    ('clickup', ARRAY['Clickup'], 0),
    ('cline and/or roo', ARRAY['Cline and/or Roo'], 0),
    ('cloud firestore', ARRAY['Cloud Firestore'], 0),
    ('cloudflare', ARRAY['Cloudflare'], 0),
    ('cockroachdb', ARRAY['Cockroachdb'], 0),
    ('coda', ARRAY['Coda'], 0),
    ('cohere: command a', ARRAY['Cohere: Command A'], 0),
    ('company-sponsored forums', ARRAY['Company-sponsored forums'], 0),
    ('composer', ARRAY['Composer'], 0),
    ('confluence', ARRAY['Confluence'], 0),
    ('cosmos db', ARRAY['Cosmos DB'], 0),
    ('cursor', ARRAY['Cursor'], 0),
    ('dart', ARRAY['Dart'], 0),
    ('databricks sql', ARRAY['Databricks SQL'], 0),
    ('datadog', ARRAY['Datadog'], 0),
    ('datomic', ARRAY['Datomic'], 0),
    ('debian', ARRAY['Debian'], 0),
    ('deepseek (r- reasoning models)', ARRAY['DeepSeek (R- Reasoning models)'], 0),
    ('deepseek (v- general purpose models)', ARRAY['DeepSeek (V- General purpose models)'], 0),
    ('delphi', ARRAY['Delphi'], 0),
    ('delphi 12+ athens', ARRAY['Delphi 12+ Athens'], 0),
    ('deno', ARRAY['Deno'], 0),
    ('dev.to', ARRAY['Dev.to'], 0),
    ('digital ocean', ARRAY['Digital Ocean'], 0),
    ('discord', ARRAY['Discord'], 0),
    ('django', ARRAY['Django'], 0),
    ('docker', ARRAY['Docker'], 0),
    ('doxygen', ARRAY['Doxygen'], 0),
    ('drupal', ARRAY['Drupal'], 0),
    ('duckdb', ARRAY['DuckDB'], 0),
    ('dynamodb', ARRAY['Dynamodb'], 0),
    ('eclipse', ARRAY['Eclipse'], 0),
    ('elasticsearch', ARRAY['Elasticsearch'], 0),
    ('elixir', ARRAY['Elixir'], 0),
    ('erlang', ARRAY['Erlang'], 0),
    ('express', ARRAY['Express'], 0),
    ('f#', ARRAY['F#'], 0),
    ('fastapi', ARRAY['FastAPI'], 0),
    ('fastify', ARRAY['Fastify'], 0),
    ('fedora', ARRAY['Fedora'], 0),
    ('firebase', ARRAY['Firebase'], 0),
    ('firebase realtime database', ARRAY['Firebase Realtime Database'], 0),
    ('flask', ARRAY['Flask'], 0),
    ('fortran', ARRAY['Fortran'], 0),
    ('gdscript', ARRAY['GDScript'], 0),
    ('gemini (flash general purpose models)', ARRAY['Gemini (Flash general purpose models)'], 0),
    ('gemini (pro reasoning models)', ARRAY['Gemini (Pro Reasoning models)'], 0),
    ('github', ARRAY['GitHub'], 0),
    ('github (public projects, not private repos)', ARRAY['GitHub (public projects, not private repos)'], 0),
    ('gitlab', ARRAY['GitLab'], 0),
    ('gleam', ARRAY['Gleam'], 0),
    ('go', ARRAY['Go'], 0),
    ('google cloud', ARRAY['Google Cloud'], 0),
    ('google colab', ARRAY['Google Colab'], 0),
    ('google gemini', ARRAY['Google Gemini'], 0),
    ('google workspace', ARRAY['Google Workspace'], 0),
    ('gradle', ARRAY['Gradle'], 0),
    ('groovy', ARRAY['Groovy'], 0),
    ('h2', ARRAY['H2'], 0),
    ('html/css', ARRAY['HTML/CSS'], 0),
    ('hacker news', ARRAY['Hacker News'], 0),
    ('hashnode', ARRAY['Hashnode'], 0),
    ('heroku', ARRAY['Heroku'], 0),
    ('homebrew', ARRAY['Homebrew'], 0),
    ('ibm cloud', ARRAY['IBM Cloud'], 0),
    ('ibm db2', ARRAY['IBM DB2'], 0),
    ('influxdb', ARRAY['InfluxDB'], 0),
    ('intellij idea', ARRAY['IntelliJ IDEA'], 0),
    ('java', ARRAY['Java'], 0),
    ('javascript', ARRAY['JavaScript'], 0),
    ('jira', ARRAY['Jira'], 0),
    ('jupyter notebook/jupyterlab', ARRAY['Jupyter Notebook/JupyterLab'], 0),
    ('kaggle', ARRAY['Kaggle'], 0),
    ('kotlin', ARRAY['Kotlin'], 0),
    ('kubernetes', ARRAY['Kubernetes'], 0),
    ('langgraph', ARRAY['LangGraph'], 0),
    ('laravel', ARRAY['Laravel'], 0),
    ('large language model', ARRAY['Large Language Model'], 0),
    ('linear', ARRAY['Linear'], 0),
    ('linkedin', ARRAY['LinkedIn'], 0),
    ('linux (non-wsl)', ARRAY['Linux (non-WSL)'], 0),
    ('lisp', ARRAY['Lisp'], 0),
    ('lovable.dev', ARRAY['Lovable.dev'], 0),
    ('lua', ARRAY['Lua'], 0),
    ('lucid (includes lucidchart)', ARRAY['Lucid (includes Lucidchart)'], 0),
    ('matlab', ARRAY['MATLAB'], 0),
    ('msbuild', ARRAY['MSBuild'], 0),
    ('macos', ARRAY['MacOS'], 0),
    ('make', ARRAY['Make'], 0),
    ('mariadb', ARRAY['MariaDB'], 0),
    ('markdown file', ARRAY['Markdown File'], 0),
    ('maven (build tool)', ARRAY['Maven (build tool)'], 0),
    ('medium', ARRAY['Medium'], 0),
    ('meta llama (all models)', ARRAY['Meta Llama (all models)'], 0),
    ('micropython', ARRAY['MicroPython'], 0),
    ('microsoft access', ARRAY['Microsoft Access'], 0),
    ('microsoft azure', ARRAY['Microsoft Azure'], 0),
    ('microsoft fabric', ARRAY['Microsoft Fabric'], 0),
    ('microsoft phi-4 models', ARRAY['Microsoft Phi-4 models'], 0),
    ('microsoft planner', ARRAY['Microsoft Planner'], 0),
    ('microsoft sql server', ARRAY['Microsoft SQL Server'], 0),
    ('miro', ARRAY['Miro'], 0),
    ('mistral ai models', ARRAY['Mistral AI models'], 0),
    ('mojo', ARRAY['Mojo'], 0),
    ('monday.com', ARRAY['Monday.com'], 0),
    ('mongodb', ARRAY['MongoDB'], 0),
    ('mysql', ARRAY['MySQL'], 0),
    ('nano', ARRAY['Nano'], 0),
    ('neo4j', ARRAY['Neo4J'], 0),
    ('neovim', ARRAY['Neovim'], 0),
    ('nestjs', ARRAY['NestJS'], 0),
    ('netlify', ARRAY['Netlify'], 0),
    ('new relic', ARRAY['New Relic'], 0),
    ('next.js', ARRAY['Next.js'], 0),
    ('ninja', ARRAY['Ninja'], 0),
    ('nixos', ARRAY['NixOS'], 0),
    ('node.js', ARRAY['Node.js'], 0),
    ('notepad++', ARRAY['Notepad++'], 0),
    ('notion', ARRAY['Notion'], 0),
    ('nuget', ARRAY['NuGet'], 0),
    ('nuxt.js', ARRAY['Nuxt.js'], 0),
    ('ocaml', ARRAY['OCaml'], 0),
    ('obsidian', ARRAY['Obsidian'], 0),
    ('odoo', ARRAY['Odoo'], 0),
    ('ollama', ARRAY['Ollama'], 0),
    ('oracle', ARRAY['Oracle'], 0),
    ('php', ARRAY['PHP'], 0),
    ('pacman', ARRAY['Pacman'], 0),
    ('perl', ARRAY['Perl'], 0),
    ('perplexity sonar models', ARRAY['Perplexity Sonar models'], 0),
    ('phoenix', ARRAY['Phoenix'], 0),
    ('phpstorm', ARRAY['PhpStorm'], 0),
    ('pip', ARRAY['Pip'], 0),
    ('pocketbase', ARRAY['Pocketbase'], 0),
    ('podman', ARRAY['Podman'], 0),
    ('poetry', ARRAY['Poetry'], 0),
    ('polars', ARRAY['Polars'], 0),
    ('pop!_os', ARRAY['Pop!_OS'], 0),
    ('postgresql', ARRAY['PostgreSQL'], 0),
    ('powershell', ARRAY['PowerShell'], 0),
    ('prolog', ARRAY['Prolog'], 0),
    ('prometheus', ARRAY['Prometheus'], 0),
    ('pycharm', ARRAY['PyCharm'], 0),
    ('pydantic', ARRAY['Pydantic'], 0),
    ('python', ARRAY['Python'], 0),
    ('r', ARRAY['R'], 0),
    ('rag', ARRAY['RAG'], 0),
    ('railway', ARRAY['Railway'], 0),
    ('react', ARRAY['React'], 0),
    ('red hat', ARRAY['Red Hat'], 0),
    ('reddit', ARRAY['Reddit'], 0),
    ('redis', ARRAY['Redis'], 0),
    ('redmine', ARRAY['Redmine'], 0),
    ('reka (flash 3 or other reka models)', ARRAY['Reka (Flash 3 or other Reka models)'], 0),
    ('rider', ARRAY['Rider'], 0),
    ('ruby', ARRAY['Ruby'], 0),
    ('ruby on rails', ARRAY['Ruby on Rails'], 0),
    ('rust', ARRAY['Rust'], 0),
    ('rustrover', ARRAY['RustRover'], 0),
    ('sql', ARRAY['SQL'], 0),
    ('sqlite', ARRAY['SQLite'], 0),
    ('scala', ARRAY['Scala'], 0),
    ('shadcn/ui', ARRAY['Shadcn/ui'], 0),
    ('slack (public channels, not work)', ARRAY['Slack (public channels, not work)'], 0),
    ('snowflake', ARRAY['Snowflake'], 0),
    ('splunk', ARRAY['Splunk'], 0),
    ('spring boot', ARRAY['Spring Boot'], 0),
    ('stack exchange', ARRAY['Stack Exchange'], 0),
    ('stack overflow', ARRAY['Stack Overflow'], 0),
    ('stack overflow for teams', ARRAY['Stack Overflow for Teams'], 0),
    ('sublime text', ARRAY['Sublime Text'], 0),
    ('substack', ARRAY['Substack'], 0),
    ('supabase', ARRAY['Supabase'], 0),
    ('svelte', ARRAY['Svelte'], 0),
    ('swift', ARRAY['Swift'], 0),
    ('swiftdata', ARRAY['SwiftData'], 0),
    ('symfony', ARRAY['Symfony'], 0),
    ('tailwind css 4', ARRAY['Tailwind CSS 4'], 0),
    ('terraform', ARRAY['Terraform'], 0),
    ('trae', ARRAY['Trae'], 0),
    ('trello', ARRAY['Trello'], 0),
    ('twitch', ARRAY['Twitch'], 0),
    ('typescript', ARRAY['TypeScript'], 0),
    ('ubuntu', ARRAY['Ubuntu'], 0),
    ('ultralytics', ARRAY['Ultralytics'], 0),
    ('vba', ARRAY['VBA'], 0),
    ('vscodium', ARRAY['VSCodium'], 0),
    ('valkey', ARRAY['Valkey'], 0),
    ('vercel', ARRAY['Vercel'], 0),
    ('vim', ARRAY['Vim'], 0),
    ('visual basic (.net)', ARRAY['Visual Basic (.Net)'], 0),
    ('visual studio', ARRAY['Visual Studio'], 0),
    ('visual studio code', ARRAY['Visual Studio Code'], 0),
    ('vite', ARRAY['Vite'], 0),
    ('vue.js', ARRAY['Vue.js'], 0),
    ('webstorm', ARRAY['WebStorm'], 0),
    ('webpack', ARRAY['Webpack'], 0),
    ('wikis', ARRAY['Wikis'], 0),
    ('windows', ARRAY['Windows'], 0),
    ('windows subsystem for linux (wsl)', ARRAY['Windows Subsystem for Linux (WSL)'], 0),
    ('windsurf', ARRAY['Windsurf'], 0),
    ('wordpress', ARRAY['WordPress'], 0),
    ('x', ARRAY['X'], 0),
    ('x grok models', ARRAY['X Grok models'], 0),
    ('xcode', ARRAY['Xcode'], 0),
    ('yandex cloud', ARRAY['Yandex Cloud'], 0),
    ('yarn', ARRAY['Yarn'], 0),
    ('youtrack', ARRAY['YouTrack'], 0),
    ('youtube', ARRAY['YouTube'], 0),
    ('zed', ARRAY['Zed'], 0),
    ('zig', ARRAY['Zig'], 0),
    ('c++23', ARRAY[]::text[], 0),
    ('hostinger', ARRAY[]::text[], 0),
    ('ios', ARRAY['iOS'], 0),
    ('ipados', ARRAY['iPadOS'], 0),
    ('jquery', ARRAY['jQuery'], 0),
    ('npm', ARRAY[]::text[], 0),
    ('openai gpt (chatbot models)', ARRAY['openAI GPT (chatbot models)'], 0),
    ('openai image generating models', ARRAY['openAI Image generating models'], 0),
    ('openai reasoning models', ARRAY['openAI Reasoning models'], 0),
    ('pnpm', ARRAY[]::text[], 0),
    ('uv', ARRAY[]::text[], 0),
    ('visionos', ARRAY['visionOS'], 0)
ON CONFLICT (name) DO UPDATE
SET aliases = EXCLUDED.aliases,
    updated_at = now();
