-- Dev-only repeatable seed data for quick matching tests.
-- Loaded via %dev Flyway location: classpath:db/dev
-- Source: arbeitnow public API

INSERT INTO mesh.mesh_node (id, created_by, node_type, title, description, searchable, created_at, updated_at)
VALUES ('d0000000-0000-0000-0000-000000000012', 'd0000000-0000-0000-0000-000000000012', 'USER', 'System: dev-seed-jobs', 'System owner for synthetic job seeds.', false, now(), now())
ON CONFLICT (id) DO UPDATE SET searchable = false, updated_at = now();

INSERT INTO identity.user_identity (id, oauth_provider, oauth_subject, node_id, can_create_job, can_manage_skills)
VALUES ('d1000000-0000-0000-0000-000000000012', 'dev-seed', 'jobs-owner', 'd0000000-0000-0000-0000-000000000012', true, false)
ON CONFLICT (id) DO NOTHING;

DELETE FROM mesh.mesh_node
WHERE created_by = 'd0000000-0000-0000-0000-000000000012' AND node_type = 'JOB';

INSERT INTO mesh.mesh_node (created_by, node_type, title, description, tags, structured_data, country, searchable, embedding, created_at, updated_at)
VALUES
('d0000000-0000-0000-0000-000000000012', 'JOB', 'Hswdbdf', 'Hswdbdf at Kubique GmbH.', ARRAY['Graphic Arts and Communication Design'], '{"external_id": "public-job-00001", "requirements_text": "Aufgaben dfdubgud dfgifhgb sdhgidfbg isdhgihd Qualifikation dhigifdhg dighiofhg idjghiohfg jdf Benefits efj efj Find Jobs in Germany on Arbeitnow", "skills_required": ["Graphic Arts and Communication Design"], "work_mode": "HYBRID", "employment_type": "CONTRACTOR", "external_url": "https://www.arbeitnow.com/jobs/companies/kubique-gmbh/hswdbdf-hamburg-201289"}'::jsonb, 'DE', true, NULL, now(), now()),
('d0000000-0000-0000-0000-000000000012', 'JOB', 'Senior Data Scientist (f/m/d)', 'Senior Data Scientist (f/m/d) at adjoe GmbH.', ARRAY['Data Scientist'], '{"external_id": "public-job-00002", "requirements_text": "adjoe is a leading mobile ad platform developing cutting-edge advertising and monetization solutions that take its app partners\u2019 business to the next level. Part of the applike group ecosystem, adjoe is home to an advanced tech stack, powerful financial backing from Bertelsmann, and a highly motivated workforce to be reckoned with. Meet Your Team: Programmatic Data Science Did you know that in-app ads are sold in a real-time auction before they get rendered in thousands of mobile apps? Dozens of ad networks compete for every single view, choosing their best ad and deciding what price to bid in just a couple hundred milliseconds. We at adjoe have developed our own ad network that takes part in this competition, going against industry giants to present our own ads. In the competitive real-time bidding landscape, the Programmatic Data Science team operates at a rapid pace, developing cutting-edge algorithms, to create systems that outperform industry giants. Our approach is deeply rooted in rigorous research into user behavior, publisher and advertiser objectives, ensuring an optimal user experience. We are a fast-moving team that rapidly translates theory into impactful solutions, using state-of-the-art technologies and collaborating closely with product and business stakeholders. What You Will Do: Architect and Refine Relevance Models : design and implement sophisticated targeting models that understand user preference within the dynamic ad tech ecosystem. Drive significant improvements in ad performance and user engagement through machine learning techniques. Explore Policy Optimization Strategies : Develop and optimize bidding policies using Bayesian method, reinforcement learning and other advanced optimization algorithms. Continuously refine these policies to maximiz", "skills_required": ["Data Scientist"], "work_mode": "ONSITE", "employment_type": "EMPLOYED", "external_url": "https://www.arbeitnow.com/jobs/companies/adjoe-gmbh/senior-data-scientist-hamburg-52350"}'::jsonb, 'IT', true, NULL, now(), now()),
('d0000000-0000-0000-0000-000000000012', 'JOB', 'Senior Data Scientist (f/m/d)', 'Senior Data Scientist (f/m/d) at JustDice GmbH.', ARRAY['Data Scientist'], '{"external_id": "public-job-00003", "requirements_text": "adjoe is a leading mobile ad platform developing cutting-edge advertising and monetization solutions that take its app partners\u2019 business to the next level. Part of the applike group ecosystem, adjoe is home to an advanced tech stack, powerful financial backing from Bertelsmann, and a highly motivated workforce to be reckoned with. Meet Your Team: Programmatic Data Science Did you know that in-app ads are sold in a real-time auction before they get rendered in thousands of mobile apps? Dozens of ad networks compete for every single view, choosing their best ad and deciding what price to bid in just a couple hundred milliseconds. We at adjoe have developed our own ad network that takes part in this competition, going against industry giants to present our own ads. In the competitive real-time bidding landscape, the Programmatic Data Science team operates at a rapid pace, developing cutting-edge algorithms, to create systems that outperform industry giants. Our approach is deeply rooted in rigorous research into user behavior, publisher and advertiser objectives, ensuring an optimal user experience. We are a fast-moving team that rapidly translates theory into impactful solutions, using state-of-the-art technologies and collaborating closely with product and business stakeholders. What You Will Do: Architect and Refine Relevance Models : design and implement sophisticated targeting models that understand user preference within the dynamic ad tech ecosystem. Drive significant improvements in ad performance and user engagement through machine learning techniques. Explore Policy Optimization Strategies : Develop and optimize bidding policies using Bayesian method, reinforcement learning and other advanced optimization algorithms. Continuously refine these policies to maximiz", "skills_required": ["Data Scientist"], "work_mode": "REMOTE", "employment_type": "CONTRACTOR", "external_url": "https://www.arbeitnow.com/jobs/companies/justdice-gmbh/senior-data-scientist-hamburg-379896"}'::jsonb, 'FR', true, NULL, now(), now()),
('d0000000-0000-0000-0000-000000000012', 'JOB', 'Editorial Product & Operations Manager (m/w/d)', 'Editorial Product & Operations Manager (m/w/d) at Berliner Verlag GmbH.', ARRAY['Product Management'], '{"external_id": "public-job-00004", "requirements_text": "Die Berliner Zeitung steht f\u00fcr unvoreingenommenen, unabh\u00e4ngigen Journalismus. Wir sind \u00fcberzeugt, dass eine kritische Presse unverzichtbare Voraussetzung einer funktionierenden Demokratie ist. Zur Verst\u00e4rkung unseres Teams suchen wir zum n\u00e4chstm\u00f6glichen Zeitpunkt einen Editorial Product &#x26; Operations Manager (m/w/d). Aufgaben Technologie-Botschafter: Du identifizierst technologische Trends (KI, CMS-Features) und koordinierst deren Implementierung. Dabei bist du der/dir prim\u00e4re Ansprechpartner:in f\u00fcr unsere Entwickler:innen und stellst sicher, dass die Vision der Redaktion technisch pr\u00e4zise verstanden wird. Performance-Monitoring &#x26; SEO: Du hast unsere technische Infrastruktur und SEO-Performance fest im Blick. Du analysierst Daten und erarbeitest gemeinsam mit der Technik Optimierungsvorschl\u00e4ge. Prozessoptimierung: Du analysierst redaktionelle Workflows und suchst nach Potenzial zur Automatisierung oder technischen Unterst\u00fctzung, um den Newsroom effizienter zu machen. Multiprojektmanagement: Du steuerst komplexe Projekte \u00fcber verschiedene Abteilungen hinweg und moderierst den Austausch zwischen Content-Ersteller:innen und Software-Ingenieur:innen. Qualifikation Du beherrschst Deutsch auf Muttersprachenniveau f\u00fcr die Arbeit in der Redaktion und kommunizierst zwingend verhandlungssicher auf Englisch, um die t\u00e4gliche Abstimmung mit unseren internationalen Entwickler-Teams reibungslos zu gestalten. Zweisprachig (Content &#x26; Code): Du verstehst die Sprache der Redaktion ebenso gut wie die Logik der Software-Entwicklung. Technisches Fundament: Fundierte Kenntnisse in SEO, Web-Technologien und Datenanalyse sind f\u00fcr dich Standard. Organisationstalent: Du bist sicher in agilen Projektmanagement-Methoden und beh\u00e4ltst auch bei parallelen Projekten k\u00fchlen Kopf. Moderatio", "skills_required": ["Product Management"], "work_mode": "HYBRID", "employment_type": "EMPLOYED", "external_url": "https://www.arbeitnow.com/jobs/companies/berliner-verlag-gmbh/editorial-product-operations-manager-berlin-371251"}'::jsonb, 'GB', true, NULL, now(), now());
