-- Dev-only repeatable seed data for quick matching tests.
-- Loaded via %dev Flyway location: classpath:db/dev
-- Source: randomuser.me + ESCO skills/occupations (public APIs)

INSERT INTO mesh.mesh_node (id, created_by, node_type, title, description, searchable, created_at, updated_at)
VALUES ('d0000000-0000-0000-0000-000000000011', 'd0000000-0000-0000-0000-000000000011', 'USER', 'System: dev-seed-users', 'System owner for synthetic user seeds.', false, now(), now())
ON CONFLICT (id) DO UPDATE SET searchable = false, updated_at = now();

INSERT INTO identity.user_identity (id, oauth_provider, oauth_subject, node_id, can_create_job, can_manage_skills)
VALUES ('d1000000-0000-0000-0000-000000000011', 'dev-seed', 'users-owner', 'd0000000-0000-0000-0000-000000000011', false, false)
ON CONFLICT (id) DO NOTHING;

DELETE FROM mesh.mesh_node
WHERE created_by = 'd0000000-0000-0000-0000-000000000011' AND node_type = 'USER' AND id <> 'd0000000-0000-0000-0000-000000000011';

INSERT INTO mesh.mesh_node (id, created_by, node_type, title, description, tags, structured_data, country, searchable, external_id, embedding, created_at, updated_at)
VALUES
('adfbdef5-8b4e-5b65-a225-017ea95993c0', 'adfbdef5-8b4e-5b65-a225-017ea95993c0', 'USER', 'Salomé Boyer', 'computer games, multimedia and software specialised seller profile derived from public datasets.', ARRAY['translate requirement concepts into visual design','development delays','develop statistical software','Taleo'], '{"email": "salome.boyer@example.com", "first_name": "Salom\u00e9", "last_name": "Boyer", "role": "computer games, multimedia and software specialised seller", "seniority": "LEAD", "skills_professional": ["translate requirement concepts into visual design", "development delays", "develop statistical software", "Taleo", "provide individual exercise programmes", "ABAP"], "tools_and_tech": ["translate requirement concepts into visual design", "development delays", "develop statistical software", "Taleo", "provide individual exercise programmes"], "skills_soft": ["Problem solving", "Adaptability", "Communication", "Mentoring"], "languages_spoken": ["English"], "work_mode": "HYBRID", "employment_type": "EMPLOYED", "learning_areas": ["AI", "Cloud Architecture"], "project_types": ["cloud migration", "platform modernization"], "hobbies": ["photography", "travel", "hiking"], "sports": ["running", "football"], "book_genres": ["business", "fiction"], "music_genres": ["classical", "rock"], "city": "Plaffeien", "timezone": "Beijing, Perth, Singapore, Hong Kong", "avatar_url": "https://randomuser.me/api/portraits/women/55.jpg", "profile_version": "2.0", "source": "randomuser.me + esco"}'::jsonb, 'US', true, 'public-user-0001', NULL, now(), now()),
('ed25f963-e876-5730-8224-ae6769bcf85e', 'ed25f963-e876-5730-8224-ae6769bcf85e', 'USER', 'Stefan Löw', 'software developer profile derived from public datasets.', ARRAY['alarm systems','wide web flexographic printing press','WizIQ','use technical drawing software'], '{"email": "stefan.low@example.com", "first_name": "Stefan", "last_name": "L\u00f6w", "role": "software developer", "seniority": "LEAD", "skills_professional": ["alarm systems", "wide web flexographic printing press", "WizIQ", "use technical drawing software", "oversee wetlands in project development", "consider the impact of material characteristics on pipeline flows"], "tools_and_tech": ["alarm systems", "wide web flexographic printing press", "WizIQ", "use technical drawing software", "oversee wetlands in project development"], "skills_soft": ["Time management", "Problem solving", "Critical thinking", "Teamwork"], "languages_spoken": ["German", "English"], "work_mode": "ONSITE", "employment_type": "EMPLOYED", "learning_areas": ["Leadership", "AI"], "project_types": ["internal tooling", "security hardening"], "hobbies": ["hiking", "music", "cooking"], "sports": ["running", "football"], "book_genres": ["fiction", "technology"], "music_genres": ["classical", "electronic"], "city": "Glinde", "timezone": "Baghdad, Riyadh, Moscow, St. Petersburg", "avatar_url": "https://randomuser.me/api/portraits/men/8.jpg", "profile_version": "2.0", "source": "randomuser.me + esco"}'::jsonb, 'DE', true, 'public-user-0002', NULL, now(), now()),
('18ff60ad-55bb-5f1b-b6b5-8f364b003c20', '18ff60ad-55bb-5f1b-b6b5-8f364b003c20', 'USER', 'Saksham Das', 'embedded systems software developer profile derived from public datasets.', ARRAY['human psychological development','interpret laboratory data in medical genetics','Chef (tools for software configuration management)','ICT performance analysis methods'], '{"email": "saksham.das@example.com", "first_name": "Saksham", "last_name": "Das", "role": "embedded systems software developer", "seniority": "LEAD", "skills_professional": ["human psychological development", "interpret laboratory data in medical genetics", "Chef (tools for software configuration management)", "ICT performance analysis methods", "create data sets", "use online tools to collaborate"], "tools_and_tech": ["human psychological development", "interpret laboratory data in medical genetics", "Chef (tools for software configuration management)", "ICT performance analysis methods", "create data sets"], "skills_soft": ["Adaptability", "Mentoring", "Teamwork", "Communication"], "languages_spoken": ["English", "Hindi"], "work_mode": "REMOTE", "employment_type": "EMPLOYED", "learning_areas": ["Cloud Architecture", "AI"], "project_types": ["customer delivery", "internal tooling"], "hobbies": ["reading", "gaming", "photography"], "sports": ["swimming", "running"], "book_genres": ["history", "fiction"], "music_genres": ["electronic", "rock"], "city": "Nellore", "timezone": "Kabul", "avatar_url": "https://randomuser.me/api/portraits/men/61.jpg", "profile_version": "2.0", "source": "randomuser.me + esco"}'::jsonb, 'IN', true, 'public-user-0003', NULL, now(), now()),
('7a7b953e-e43d-58ad-8cb3-961a289275f8', '7a7b953e-e43d-58ad-8cb3-961a289275f8', 'USER', 'علی رضا كامياران', 'software analyst profile derived from public datasets.', ARRAY['analyse experimental laboratory data','data extraction, transformation and loading tools','Common Lisp','ground segment'], '{"email": "aalyrd.kmyrn@example.com", "first_name": "\u0639\u0644\u06cc \u0631\u0636\u0627", "last_name": "\u0643\u0627\u0645\u064a\u0627\u0631\u0627\u0646", "role": "software analyst", "seniority": "MID", "skills_professional": ["analyse experimental laboratory data", "data extraction, transformation and loading tools", "Common Lisp", "ground segment", "use colour printing programs", "urban planning"], "tools_and_tech": ["analyse experimental laboratory data", "data extraction, transformation and loading tools", "Common Lisp", "ground segment", "use colour printing programs"], "skills_soft": ["Teamwork", "Mentoring", "Adaptability", "Critical thinking"], "languages_spoken": ["English"], "work_mode": "HYBRID", "employment_type": "EMPLOYED", "learning_areas": ["Data Engineering", "Cloud Architecture"], "project_types": ["internal tooling", "platform modernization"], "hobbies": ["hiking", "photography", "chess"], "sports": ["tennis", "swimming"], "book_genres": ["business", "technology"], "music_genres": ["electronic", "jazz"], "city": "\u0627\u0631\u0648\u0645\u06cc\u0647", "timezone": "Abu Dhabi, Muscat, Baku, Tbilisi", "avatar_url": "https://randomuser.me/api/portraits/men/61.jpg", "profile_version": "2.0", "source": "randomuser.me + esco"}'::jsonb, 'US', true, 'public-user-0004', NULL, now(), now()),
('590afffd-5944-5dba-901d-f233e8a8bf19', '590afffd-5944-5dba-901d-f233e8a8bf19', 'USER', 'مانی گلشن', 'computer software and multimedia shop manager profile derived from public datasets.', ARRAY['develop library educational programs','computer engineering','COBOL','manage digital documents'], '{"email": "mny.glshn@example.com", "first_name": "\u0645\u0627\u0646\u06cc", "last_name": "\u06af\u0644\u0634\u0646", "role": "computer software and multimedia shop manager", "seniority": "JUNIOR", "skills_professional": ["develop library educational programs", "computer engineering", "COBOL", "manage digital documents", "manage data", "R"], "tools_and_tech": ["develop library educational programs", "computer engineering", "COBOL", "manage digital documents", "manage data"], "skills_soft": ["Critical thinking", "Stakeholder management", "Adaptability", "Time management"], "languages_spoken": ["English"], "work_mode": "ONSITE", "employment_type": "EMPLOYED", "learning_areas": ["Data Engineering", "DevSecOps"], "project_types": ["security hardening", "customer delivery"], "hobbies": ["cooking", "chess", "photography"], "sports": ["cycling", "yoga"], "book_genres": ["history", "business"], "music_genres": ["jazz", "rock"], "city": "\u0634\u0647\u0631\u06cc\u0627\u0631", "timezone": "Western Europe Time, London, Lisbon, Casablanca", "avatar_url": "https://randomuser.me/api/portraits/men/42.jpg", "profile_version": "2.0", "source": "randomuser.me + esco"}'::jsonb, 'US', true, 'public-user-0005', NULL, now(), now());
