{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "peoplemesh.postgresqlServiceName" . }}
  labels:
    {{- include "peoplemesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "peoplemesh.name" . }}
    app.kubernetes.io/component: postgresql
{{- end }}
