package org.peoplemesh.mcp;

import io.quarkiverse.mcp.server.TextContent;
import io.quarkiverse.mcp.server.Tool;
import io.quarkus.security.Authenticated;
import org.peoplemesh.domain.dto.ProfileSchema;
import org.peoplemesh.service.ProfileService;
import jakarta.inject.Inject;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.jboss.logging.Logger;

import java.util.UUID;

public class ProfileTools {

    private static final Logger LOG = Logger.getLogger(ProfileTools.class);
    private static final int MAX_PAYLOAD_SIZE = 64 * 1024;

    @Inject
    UserResolver userResolver;

    @Inject
    ProfileService profileService;

    @Inject
    ObjectMapper objectMapper;

    @Tool(name = "peoplemesh_submit_profile",
          description = "Submit an approved professional profile to PeopleMesh. Requires a valid consent_token and the profile JSON generated by Claude from conversation memory.")
    @Authenticated
    public TextContent submitProfile(String profileJson, String consentToken) {
        try {
            if (profileJson == null || profileJson.isBlank()) {
                return new TextContent("Error: profileJson is required.");
            }
            if (profileJson.length() > MAX_PAYLOAD_SIZE) {
                return new TextContent("Error: profile payload exceeds maximum size.");
            }
            if (consentToken == null || consentToken.isBlank()) {
                return new TextContent("Error: consentToken is required.");
            }
            UUID userId = userResolver.resolveUserId();
            ProfileSchema schema = objectMapper.readValue(profileJson, ProfileSchema.class);
            profileService.submitProfile(userId, schema, consentToken, null);
            return new TextContent("Profile submitted successfully. You are now searchable by other professionals.");
        } catch (SecurityException e) {
            return new TextContent("Error: " + e.getMessage());
        } catch (Exception e) {
            LOG.error("Failed to submit profile", e);
            return new TextContent("Failed to submit profile. Please check the payload format and try again.");
        }
    }

    @Tool(name = "peoplemesh_get_my_profile",
          description = "Retrieve your current PeopleMesh professional profile.")
    @Authenticated
    public TextContent getMyProfile() {
        try {
            UUID userId = userResolver.resolveUserId();
            return profileService.getProfile(userId)
                    .map(schema -> {
                        try {
                            return new TextContent(objectMapper.writerWithDefaultPrettyPrinter()
                                    .writeValueAsString(schema));
                        } catch (Exception e) {
                            LOG.error("Error serializing profile", e);
                            return new TextContent("Error serializing profile.");
                        }
                    })
                    .orElse(new TextContent("No profile found. Use peoplemesh_submit_profile to create one."));
        } catch (SecurityException e) {
            return new TextContent("Error: " + e.getMessage());
        } catch (Exception e) {
            LOG.error("Error retrieving profile", e);
            return new TextContent("Error retrieving profile. Please try again later.");
        }
    }

    @Tool(name = "peoplemesh_update_my_profile",
          description = "Update fields in your PeopleMesh profile. Send a partial profile JSON with only the fields to update.")
    @Authenticated
    public TextContent updateMyProfile(String profileJson) {
        try {
            if (profileJson == null || profileJson.isBlank()) {
                return new TextContent("Error: profileJson is required.");
            }
            if (profileJson.length() > MAX_PAYLOAD_SIZE) {
                return new TextContent("Error: profile payload exceeds maximum size.");
            }
            UUID userId = userResolver.resolveUserId();
            ProfileSchema updates = objectMapper.readValue(profileJson, ProfileSchema.class);
            return profileService.updateProfile(userId, updates)
                    .map(p -> new TextContent("Profile updated successfully."))
                    .orElse(new TextContent("No profile found to update."));
        } catch (SecurityException e) {
            return new TextContent("Error: " + e.getMessage());
        } catch (Exception e) {
            LOG.error("Failed to update profile", e);
            return new TextContent("Failed to update profile. Please check the payload format and try again.");
        }
    }

    @Tool(name = "peoplemesh_delete_my_profile",
          description = "Delete your PeopleMesh profile and all associated data. This action is irreversible after 30 days.")
    @Authenticated
    public TextContent deleteMyProfile() {
        try {
            UUID userId = userResolver.resolveUserId();
            boolean deleted = profileService.deleteProfile(userId);
            return deleted
                    ? new TextContent("Profile deleted. Data will be permanently removed within 30 days.")
                    : new TextContent("No profile found to delete.");
        } catch (SecurityException e) {
            return new TextContent("Error: " + e.getMessage());
        } catch (Exception e) {
            LOG.error("Failed to delete profile", e);
            return new TextContent("Failed to delete profile. Please try again later.");
        }
    }
}
